2019-12-11 11:48:51,479 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:48:51,479 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:48:51,484 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:48:51,491 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:48:51,497 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:48:51,504 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:48:51,514 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:48:51,524 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:49:26,377 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
2019-12-11 11:49:26,377 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
2019-12-11 11:49:26,378 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
2019-12-11 11:49:26,376 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
2019-12-11 11:49:26,377 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
2019-12-11 11:49:26,377 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
2019-12-11 11:49:26,376 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined
    main()
  File "../tools/main.py", line 64, in main
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
2019-12-11 11:49:26,376 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined
    main()
  File "../tools/main.py", line 64, in main
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined
    main()
  File "../tools/main.py", line 64, in main
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined
    logger().info("=> rank {} of {} jobs, in {}".format(
  File "/mnt/lustre/guanrui/dev/fix_scripts/parrots.example/models/imagenet/utils/misc.py", line 74, in get_root_logger
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined
    rank, _ = get_dist_info()
NameError: name 'get_dist_info' is not defined
12/11/19 11:49:26.554 (P334550.T334550) [I] parrots exit with unhandled error
12/11/19 11:49:26.553 (P334543.T334543) [I] parrots exit with unhandled error
12/11/19 11:49:26.553 (P334546.T334546) [I] parrots exit with unhandled error
12/11/19 11:49:26.553 (P334547.T334547) [I] parrots exit with unhandled error
12/11/19 11:49:26.553 (P334549.T334549) [I] parrots exit with unhandled error
12/11/19 11:49:26.554 (P334544.T334544) [I] parrots exit with unhandled error
12/11/19 11:49:26.554 (P334545.T334545) [I] parrots exit with unhandled error
12/11/19 11:49:26.553 (P334548.T334548) [I] parrots exit with unhandled error
srun: error: SH-IDC1-10-5-31-38: tasks 0-5,7: Exited with exit code 1
srun: error: SH-IDC1-10-5-31-38: task 6: Exited with exit code 1
