2019-12-11 11:42:38,797 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:42:38,797 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:42:38,798 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:42:38,801 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:42:38,808 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:42:38,814 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:42:38,822 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:42:38,828 [32mINFO[0m: Parrots 0.4.0 | Git hash: 4ec10596 | Compute hash: 3ec76b2d[0m
2019-12-11 11:43:19,475 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
2019-12-11 11:43:19,475 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
2019-12-11 11:43:19,473 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
2019-12-11 11:43:19,471 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
2019-12-11 11:43:19,471 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
2019-12-11 11:43:19,475 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
2019-12-11 11:43:19,476 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
2019-12-11 11:43:19,471 [31mERROR[0m: Uncaught exception: 
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'[0m
Traceback (most recent call last):
  File "../tools/main.py", line 291, in <module>
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    main()
  File "../tools/main.py", line 64, in main
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'
    logger.info("=> rank {} of {} jobs, in {}".format(
AttributeError: 'function' object has no attribute 'info'
12/11/19 11:43:19.665 (P333766.T333766) [I] parrots exit with unhandled error
12/11/19 11:43:19.664 (P333771.T333771) [I] parrots exit with unhandled error
12/11/19 11:43:19.665 (P333764.T333764) [I] parrots exit with unhandled error
12/11/19 11:43:19.664 (P333767.T333767) [I] parrots exit with unhandled error
12/11/19 11:43:19.665 (P333770.T333770) [I] parrots exit with unhandled error
12/11/19 11:43:19.664 (P333765.T333765) [I] parrots exit with unhandled error
12/11/19 11:43:19.665 (P333768.T333768) [I] parrots exit with unhandled error
12/11/19 11:43:19.664 (P333769.T333769) [I] parrots exit with unhandled error
srun: error: SH-IDC1-10-5-31-38: tasks 1-7: Exited with exit code 1
srun: error: SH-IDC1-10-5-31-38: task 0: Exited with exit code 1
